<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> <html> <head> <title>FileNotFoundError: [Errno 2] No such file or directory: &#x27;save_file.txt&#x27; // Werkzeug Debugger</title> <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css" type="text/css"> <!-- We need to make sure this has a favicon so that the debugger does not accidentally trigger a request to /favicon.ico which might change the application's state. --> <link rel="shortcut icon" href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png"> <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script> <script type="text/javascript"> var TRACEBACK = 2668440556688, CONSOLE_MODE = false, EVALEX = true, EVALEX_TRUSTED = false, SECRET = "8IzPS0lEYc4wyUlfDBMT"; </script> </head> <body style="background-color: #fff"> <div class="debugger"> <h1>FileNotFoundError</h1> <div class="detail"> <p class="errormsg">FileNotFoundError: [Errno 2] No such file or directory: &#x27;save_file.txt&#x27;</p> </div> <h2 class="traceback">Traceback <em>(most recent call last)</em></h2> <div class="traceback"> <h3></h3> <ul><li><div class="frame" id="frame-2668442547440"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">2091</em>, in <code class="function">__call__</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>def __call__(self, environ: dict, start_response: t.Callable) -&gt; t.Any:</pre> <pre class="line before"><span class="ws"> </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre> <pre class="line before"><span class="ws"> </span>WSGI application. This calls :meth:`wsgi_app`, which can be</pre> <pre class="line before"><span class="ws"> </span>wrapped to apply middleware.</pre> <pre class="line before"><span class="ws"> </span>&quot;&quot;&quot;</pre> <pre class="line current"><span class="ws"> </span>return self.wsgi_app(environ, start_response)</pre></div> </div> <li><div class="frame" id="frame-2668442547488"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">2076</em>, in <code class="function">wsgi_app</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>try:</pre> <pre class="line before"><span class="ws"> </span>ctx.push()</pre> <pre class="line before"><span class="ws"> </span>response = self.full_dispatch_request()</pre> <pre class="line before"><span class="ws"> </span>except Exception as e:</pre> <pre class="line before"><span class="ws"> </span>error = e</pre> <pre class="line current"><span class="ws"> </span>response = self.handle_exception(e)</pre> <pre class="line after"><span class="ws"> </span>except: # noqa: B001</pre> <pre class="line after"><span class="ws"> </span>error = sys.exc_info()[1]</pre> <pre class="line after"><span class="ws"> </span>raise</pre> <pre class="line after"><span class="ws"> </span>return response(environ, start_response)</pre> <pre class="line after"><span class="ws"> </span>finally:</pre></div> </div> <li><div class="frame" id="frame-2668442547680"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py"</cite>, line <em class="line">165</em>, in <code class="function">wrapped_function</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span># Wrap exception handlers with cross_origin</pre> <pre class="line before"><span class="ws"> </span># These error handlers will still respect the behavior of the route</pre> <pre class="line before"><span class="ws"> </span>if options.get(&#x27;intercept_exceptions&#x27;, True):</pre> <pre class="line before"><span class="ws"> </span>def _after_request_decorator(f):</pre> <pre class="line before"><span class="ws"> </span>def wrapped_function(*args, **kwargs):</pre> <pre class="line current"><span class="ws"> </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre> <pre class="line after"><span class="ws"> </span>return wrapped_function</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"> </span>if hasattr(app, &#x27;handle_exception&#x27;):</pre> <pre class="line after"><span class="ws"> </span>app.handle_exception = _after_request_decorator(</pre> <pre class="line after"><span class="ws"> </span>app.handle_exception)</pre></div> </div> <li><div class="frame" id="frame-2668442547584"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">2073</em>, in <code class="function">wsgi_app</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>ctx = self.request_context(environ)</pre> <pre class="line before"><span class="ws"> </span>error: t.Optional[BaseException] = None</pre> <pre class="line before"><span class="ws"> </span>try:</pre> <pre class="line before"><span class="ws"> </span>try:</pre> <pre class="line before"><span class="ws"> </span>ctx.push()</pre> <pre class="line current"><span class="ws"> </span>response = self.full_dispatch_request()</pre> <pre class="line after"><span class="ws"> </span>except Exception as e:</pre> <pre class="line after"><span class="ws"> </span>error = e</pre> <pre class="line after"><span class="ws"> </span>response = self.handle_exception(e)</pre> <pre class="line after"><span class="ws"> </span>except: # noqa: B001</pre> <pre class="line after"><span class="ws"> </span>error = sys.exc_info()[1]</pre></div> </div> <li><div class="frame" id="frame-2668442547728"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">1518</em>, in <code class="function">full_dispatch_request</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>request_started.send(self)</pre> <pre class="line before"><span class="ws"> </span>rv = self.preprocess_request()</pre> <pre class="line before"><span class="ws"> </span>if rv is None:</pre> <pre class="line before"><span class="ws"> </span>rv = self.dispatch_request()</pre> <pre class="line before"><span class="ws"> </span>except Exception as e:</pre> <pre class="line current"><span class="ws"> </span>rv = self.handle_user_exception(e)</pre> <pre class="line after"><span class="ws"> </span>return self.finalize_request(rv)</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"> </span>def finalize_request(</pre> <pre class="line after"><span class="ws"> </span>self,</pre> <pre class="line after"><span class="ws"> </span>rv: t.Union[ResponseReturnValue, HTTPException],</pre></div> </div> <li><div class="frame" id="frame-2668442547632"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py"</cite>, line <em class="line">165</em>, in <code class="function">wrapped_function</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span># Wrap exception handlers with cross_origin</pre> <pre class="line before"><span class="ws"> </span># These error handlers will still respect the behavior of the route</pre> <pre class="line before"><span class="ws"> </span>if options.get(&#x27;intercept_exceptions&#x27;, True):</pre> <pre class="line before"><span class="ws"> </span>def _after_request_decorator(f):</pre> <pre class="line before"><span class="ws"> </span>def wrapped_function(*args, **kwargs):</pre> <pre class="line current"><span class="ws"> </span>return cors_after_request(app.make_response(f(*args, **kwargs)))</pre> <pre class="line after"><span class="ws"> </span>return wrapped_function</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"> </span>if hasattr(app, &#x27;handle_exception&#x27;):</pre> <pre class="line after"><span class="ws"> </span>app.handle_exception = _after_request_decorator(</pre> <pre class="line after"><span class="ws"> </span>app.handle_exception)</pre></div> </div> <li><div class="frame" id="frame-2668442547824"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">1516</em>, in <code class="function">full_dispatch_request</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>self.try_trigger_before_first_request_functions()</pre> <pre class="line before"><span class="ws"> </span>try:</pre> <pre class="line before"><span class="ws"> </span>request_started.send(self)</pre> <pre class="line before"><span class="ws"> </span>rv = self.preprocess_request()</pre> <pre class="line before"><span class="ws"> </span>if rv is None:</pre> <pre class="line current"><span class="ws"> </span>rv = self.dispatch_request()</pre> <pre class="line after"><span class="ws"> </span>except Exception as e:</pre> <pre class="line after"><span class="ws"> </span>rv = self.handle_user_exception(e)</pre> <pre class="line after"><span class="ws"> </span>return self.finalize_request(rv)</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"> </span>def finalize_request(</pre></div> </div> <li><div class="frame" id="frame-2668442547872"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py"</cite>, line <em class="line">1502</em>, in <code class="function">dispatch_request</code></h4> <div class="source library"><pre class="line before"><span class="ws"> </span>getattr(rule, &quot;provide_automatic_options&quot;, False)</pre> <pre class="line before"><span class="ws"> </span>and req.method == &quot;OPTIONS&quot;</pre> <pre class="line before"><span class="ws"> </span>):</pre> <pre class="line before"><span class="ws"> </span>return self.make_default_options_response()</pre> <pre class="line before"><span class="ws"> </span># otherwise dispatch to the handler for that endpoint</pre> <pre class="line current"><span class="ws"> </span>return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"> </span>def full_dispatch_request(self) -&gt; Response:</pre> <pre class="line after"><span class="ws"> </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre> <pre class="line after"><span class="ws"> </span>pre and postprocessing as well as HTTP exception catching and</pre> <pre class="line after"><span class="ws"> </span>error handling.</pre></div> </div> <li><div class="frame" id="frame-2668442547920"> <h4>File <cite class="filename">"C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\api.py"</cite>, line <em class="line">18</em>, in <code class="function">get_datos</code></h4> <div class="source "><pre class="line before"><span class="ws"> </span>return &#x27;Hola mundo, que tal&#x27;</pre> <pre class="line before"><span class="ws"></span> </pre> <pre class="line before"><span class="ws"></span> </pre> <pre class="line before"><span class="ws"></span>@app.route(&#x27;/datos&#x27;, methods=[&#x27;GET&#x27;])</pre> <pre class="line before"><span class="ws"></span>def get_datos():</pre> <pre class="line current"><span class="ws"> </span>save_file = open(&#x27;save_file.txt&#x27;, &#x27;r+&#x27;)</pre> <pre class="line after"><span class="ws"> </span>return Response(status=200,</pre> <pre class="line after"><span class="ws"> </span>response=save_file.read(),</pre> <pre class="line after"><span class="ws"> </span>content_type=&#x27;text/plain&#x27;)</pre> <pre class="line after"><span class="ws"></span> </pre> <pre class="line after"><span class="ws"></span> </pre></div> </div> </ul> <blockquote>FileNotFoundError: [Errno 2] No such file or directory: &#x27;save_file.txt&#x27;</blockquote> </div> <div class="plain"> <p> This is the Copy/Paste friendly version of the traceback. </p> <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last): File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 2091, in __call__ return self.wsgi_app(environ, start_response) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 2076, in wsgi_app response = self.handle_exception(e) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py&quot;, line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 2073, in wsgi_app response = self.full_dispatch_request() File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py&quot;, line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 1516, in full_dispatch_request rv = self.dispatch_request() File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py&quot;, line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File &quot;C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\api.py&quot;, line 18, in get_datos save_file = open(&#x27;save_file.txt&#x27;, &#x27;r+&#x27;) FileNotFoundError: [Errno 2] No such file or directory: &#x27;save_file.txt&#x27;</textarea> </div> <div class="explanation"> The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error. <span class="nojavascript"> If you enable JavaScript you can also use additional features such as code execution (if the evalex feature is enabled), automatic pasting of the exceptions and much more.</span> </div> <div class="footer"> Brought to you by <strong class="arthur">DON'T PANIC</strong>, your friendly Werkzeug powered traceback interpreter. </div> </div> <div class="pin-prompt"> <div class="inner"> <h3>Console Locked</h3> <p> The console is locked and needs to be unlocked by entering the PIN. You can find the PIN printed out on the standard output of your shell that runs the server. <form> <p>PIN: <input type=text name=pin size=14> <input type=submit name=btn value="Confirm Pin"> </form> </div> </div> </body> </html> <!-- Traceback (most recent call last): File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 2091, in __call__ return self.wsgi_app(environ, start_response) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 2076, in wsgi_app response = self.handle_exception(e) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\venv1\Lib\site-packages\flask\app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "C:\Users\Melissa\Dropbox\Mi PC (LAPTOP-VVMFAU3C)\Desktop\DIEGO\proyectos oficial\python\IPC2_Proyecto3_202003975\api.py", line 18, in get_datos save_file = open('save_file.txt', 'r+') FileNotFoundError: [Errno 2] No such file or directory: 'save_file.txt' -->